name: Deploy FastAPI on Linux Server

on:
  push:
    branches:
      - main #Runs on push to main

jobs:
  deploy:
    name: main
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/realzy.pem
          chmod 600 ~/.ssh/realzy.pem

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/realzy.pem ubuntu@${{ secrets.SERVER_IP }} << 'EOF'
            cd /home/ubuntu/hngx-stage2-fastapi-book-project
            sudo systemctl stop fastapi
            git pull origin main
            python3 -m venv venv
            source venv/bin/activate
            pip install -r requirements.txt
            sudo systemctl daemon-reload
            sudo systemctl restart fastapi
            sudo systemctl status fastapi --no-pager --lines=50
          EOF
