name: Deploy FastAPI on Linux Server

on: [push]
jobs:
  deploy:
    name: Deploy main
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SSH_USER }}
          username: linuxserver.io
          key: ${{ secrets.SSH_KEY }}
          script: cd /hngx-stage2-fastapi-book-project
              cd fastapi-book-project
              git pull origin test-main
              source venv/bin/activate
              pip install -r requirements.txt
              sudo systemctl restart fastapi